# Source: vault-instance/templates/role.yaml
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vault-secrets
  annotations:
    meta.helm.sh/release-name: 'vault-instance'
  namespace: jx-vault
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - "*"
